name: vision_x_flutter
description: "VisionX - 视界"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.1
  http: ^1.2.0
  go_router: ^14.2.3
  cached_network_image: ^3.4.1
  video_player: ^2.9.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  dio: ^5.9.0
  cached_video_player_plus: 4.0.3
  provider: ^6.1.5+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.4.6
  flutter_animate: ^4.5.0
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  window_size: ^0.1.0
  window_manager: ^0.5.1
  package_info_plus: ^8.0.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/